--Tables Created in BIGBEAR Schema for class assignment
CREATE TABLE BIGBEAR.MEMBER(
MEM_NUM INT PRIMARY KEY,
MEM_LNAME VARCHAR(20) NOT NULL,
MEM_FNAME VARCHAR(20) NOT NULL,
MEM_STREET VARCHAR(30),
MEM_CITY VARCHAR(30),
MEM_STATE CHAR(2) DEFAULT 'TN',
MEM_ZIP CHAR(5)
);



SELECT * FROM BIGBEAR.MEMBER;

CREATE TABLE BIGBEAR.ACCOUNT(
ACC_NUM VARCHAR(7) PRIMARY KEY,
ACC_OPENDATE DATE DEFAULT GETDATE(),
ACC_BALANCE DECIMAL(10,2),
ACC_LIMIT DECIMAL(10,2) DEFAULT 5000 NOT NULL,
MEM_NUM INT NOT NULL,
CONSTRAINT ACCOUNT_MEM_NUM_FK FOREIGN KEY (MEM_NUM) REFERENCES BIGBEAR.MEMBER);
