/*	Usage of TSQL Cursor for Class Assignment to Locate a Patron ID in DB and
	return corresponding book number and title stored in Book table in FACT Schema */
DECLARE @PATID INT = 1229, @COUNTER INT,@BOOKTITLE VARCHAR(30), @BOOKNUMBER INT;
DECLARE DBCURSOR CURSOR FOR
SELECT BOOK_NUM,BOOK_TITLE FROM FACT.BOOK WHERE PAT_ID = @PATID

BEGIN
OPEN DBCURSOR;

FETCH NEXT FROM DBCURSOR INTO @BOOKNUMBER,@BOOKTITLE;
		
		WHILE @@FETCH_STATUS = 0
			BEGIN
				PRINT CONCAT(@PATID,' ', @BOOKNUMBER,' ',@BOOKTITLE);
				FETCH NEXT FROM DBCURSOR INTO @BOOKNUMBER,@BOOKTITLE;
			END
END
CLOSE DBCURSOR;
DEALLOCATE DBCORSOR;
